security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/admin
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                check_path: /admin/login_check
                csrf_provider: form.csrf_provider
            logout:
                path: fos_user_security_logout
                target: /admin
            anonymous:    ~

    access_control:
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/resetting, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
