olesnica_admin_index:
    path:     /
    defaults: { _controller: OlesnicaAdminBundle:Index:index }

olesnica_admin_home:
    path:     /uvod
    defaults: { _controller: OlesnicaAdminBundle:Home:index }

olesnica_admin_about:
    path:     /o-souboru
    defaults: { _controller: OlesnicaAdminBundle:About:index }

olesnica_admin_repertoire:
    path:     /repertoar
    defaults: { _controller: OlesnicaAdminBundle:Repertoire:index }

olesnica_admin_music:
    path:     /hudba
    defaults: { _controller: OlesnicaAdminBundle:Music:index }

olesnica_admin_events:
    path:     /akce
    defaults: { _controller: OlesnicaAdminBundle:Event:index }

olesnica_admin_events_new:
    path: /akce/nova-akce
    defaults: { _controller: OlesnicaAdminBundle:Event:edit, event: null }

olesnica_admin_events_edit:
    path: /akce/{id}
    defaults: { _controller: OlesnicaAdminBundle:Event:edit }

olesnica_admin_events_delete:
    path: /akce/{id}/smazat
    defaults: { _controller: OlesnicaAdminBundle:Event:delete }

olesnica_admin_gallery:
    path:     /galerie
    defaults: { _controller: OlesnicaAdminBundle:Gallery:index }
