Olesnica\AdminBundle\Entity\Event:
    constraints:
        - Olesnica\AdminBundle\Validator\Constraints\CheckFinishDateTime: ~
    properties:
        title:
            - NotBlank: ~
        startDate:
            - NotNull: ~
        location:
            - NotBlank: ~
        shortDescription:
            - NotBlank: ~

Olesnica\AdminBundle\Entity\Attachment:
    properties:
        title:
            - NotBlank: ~
        file:
            - NotBlank:
                groups: [file]
        path:
            - NotBlank:
                groups: [path]
