Olesnica\AdminBundle\Entity\Event:
    constraints:
        - Olesnica\AdminBundle\Validator\Constraints\CheckFinishDateTime: ~
    properties:
        title:
            - NotBlank: ~
        startDate:
            - NotNull: ~
        location:
            - NotBlank: ~
        shortDescription:
            - NotBlank: ~

Olesnica\AdminBundle\Entity\Attachment:
    properties:
        title:
            - NotBlank: ~
        file:
            - NotBlank:
                groups: [file]
        path:
            - NotBlank:
                groups: [path]

Olesnica\AdminBundle\Entity\About:
    properties:
        aboutTitle:
            - NotBlank: ~
        aboutText:
            - NotBlank: ~
        historyTitle:
            - NotBlank: ~
        historyText:
            - NotBlank: ~

Olesnica\AdminBundle\Entity\Home:
    properties:
        welcomeTitle:
            - NotBlank: ~
        welcomeText:
            - NotBlank: ~
        repertoireTitle:
            - NotBlank: ~
        repertoireText:
            - NotBlank: ~
        rideOfKingsTitle:
            - NotBlank: ~
        rideOfKingsText:
            - NotBlank: ~

Olesnica\AdminBundle\Entity\Music:
    properties:
        musicTitle:
            - NotBlank: ~
        musicText:
            - NotBlank: ~

Olesnica\AdminBundle\Entity\Repertiore:
    properties:
        repertoireTitle:
            - NotBlank: ~
        repertoireText:
            - NotBlank: ~
